### ISSUE TITLE
SPI_BEGIN() and SPI_END() Missing in mcp2515_read_canMsg

### ISSUE THREAD

**Issue by zwells** [Seeed-Studio/Seeed_Arduino_CAN#103]
SPI_BEGIN() and SPI_END() need to be added to mcp2515_read_canMsg in mcp_can.cpp for some boards to read without hanging (i.e. nRF52 in my case).

`void MCP_CAN::mcp2515_read_canMsg( const byte buffer_load_addr, volatile unsigned long *id, volatile byte *ext, volatile byte *rtrBit, volatile byte *len, volatile byte *buf)        /* read can msg                 */
{
  byte tbufdata[4];
  byte i;
  SPI_BEGIN();              //ADDED
  MCP2515_SELECT();
  spi_readwrite(buffer_load_addr);
  // mcp2515 has auto-increment of address-pointer
  for (i = 0; i < 4; i++) tbufdata[i] = spi_read();
  *rtrBit=(tbufdata[3]&0x08 ? 1 : 0 );
  *id = (tbufdata[MCP_SIDH] << 3) + (tbufdata[MCP_SIDL] >> 5);
  if ( (tbufdata[MCP_SIDL] & MCP_TXB_EXIDE_M) ==  MCP_TXB_EXIDE_M )
  {
    /* extended id                  */
    *id = (*id << 2) + (tbufdata[MCP_SIDL] & 0x03);
    *id = (*id << 8) + tbufdata[MCP_EID8];
    *id = (*id << 8) + tbufdata[MCP_EID0];
    *ext = 1;
  }
  *len=spi_read() & MCP_DLC_MASK;
  for (i = 0; i < *len && i<CAN_MAX_CHAR_IN_MESSAGE; i++) {
    buf[i] = spi_read();
  }
  MCP2515_UNSELECT();
  SPI_END();                      //ADDED
}`

**Comment by Pillar1989** [comment]
I'm sorry, your question is so confusing that I can't see what you're saying?  If you feel you need to continue the discussion, you can continue to reopen the issues, I recommend changing the format of the issues, I recommend using markdown
