### ISSUE TITLE
cannot declare variable 'CAN' to be of abstract type 'MCP_CAN' 

### ISSUE THREAD

**Issue by mjat2020** [Seeed-Studio/Seeed_Arduino_CAN#106]
**Describe the bug**
cannot declare variable 'CAN' to be of abstract type 'MCP_CAN' 

I got this error while compiling through arduino IDE while declaring the class object by this header file.

Reffered this code from https://www.electronicshub.org/arduino-mcp2515-can-bus-tutorial/

**Comment by Pillar1989** [comment]
We have recently updated our code and I would suggest modifying it to accommodate the latest software. If you are not willing to modify anything, I suggest you are using this branch of the code.
https://github.com/Seeed-Studio/Seeed_Arduino_CAN/tree/old

**Comment by Ipsitakoley** [comment]
@Pillar1989 Can you please provide the link where we can get the latest library and sample code to accommodate the changes?

**Comment by Pillar1989** [comment]
@Ipsitakoley  `master` branch is the latest library.
