### ISSUE TITLE
Is it posible to Tx and Rx more than 8 bytes in one packet/frame

### ISSUE THREAD

**Issue by Wodie** [Seeed-Studio/Seeed_Arduino_CAN#110]
Hi, I am looking for  way to change the Tx and Rx size to more than 8 bytes in one packet/frame, been trying some changes but no lucky. Thank you.

**Comment by turmary** [comment]
A CAN 2.0/MCP2515 frame can only carry up to 8 bytes data.
If you want transfer more, please send more than one times.
