### ISSUE TITLE
A question with CS pin 

### ISSUE THREAD

**Issue by sundar19** [Seeed-Studio/Seeed_Arduino_CAN#112]
// the cs pin of the version after v1.1 is default to D9
// v0.9b and v1.0 is default D10

I tried using D10 with arduino UNO , but was unsuccessful to receive CAN data whereas when I tried to use D9 I got the CAN data. Whereas the hardware specifications say that UNO has its CS pin at D10 , Can anyone please brief on this!
Thanks!!!

**Comment by turmary** [comment]
UNO D10 pin as CS pin, is just a software CS(use GPIO as CS), not the SPI hardware feature.
D9 as CS pin, can be a hardware CS(using /SS feature) or software CS pin(using GPIO feature).

**Comment by sundar19** [comment]
Thank you so much
