### ISSUE TITLE
CAN Interrupt Read Faulty

### ISSUE THREAD

**Issue by georgiboby** [Seeed-Studio/Seeed_Arduino_CAN#113]
**Describe the bug**
Interrupt Reading of MCP2515 with Arduino doesn't work reliably. 

**To Reproduce**
Try overloading the Bus and receive at one End. After a few messages, the Arduino Will not go into the ISR as the Interrupt Pin always remains low. Thus the Arduino will not read any more messages.

**Reason**
This is because MCP2515 interrupt doesn't work as a trigger interrupt and stays low as long as there is a message in the Buffer. However arduino expects a Pulse everytime a message is added to the Buffer.

The Correct way is to poll the MCP2515 Interrupt Pin in loop and whenever it is LOW, Read the CAN Messages.

**Comment by Pillar1989** [comment]
@georgiboby 
@turmary  is in the middle of the Chinese New Year holiday, and he will deal with your questions the first time he returns to the office. Thank you very much for waiting.

**Comment by turmary** [comment]
hi @georgiboby 
I tested the example examples/receive_interrupt/receive_interrupt.ino by following your reproduce steps on Arduino UNO,
But not found the stop of reading messages.
Did you modified the example code in your test?
