### ISSUE TITLE
Signed int , 16 bit int & float in can bus

### ISSUE THREAD

**Issue by sundar19** [Seeed-Studio/Seeed_Arduino_CAN#119]
Hi, 
I am unable to send signed int , 16 bit int & float data type using this library. Can you please let me know how to send and receive these values.? If i send signed int or float it is interpreted differently on the receiving side .
Thank you

**Comment by Pillar1989** [comment]
This question has nothing to do with the software, just some C programming techniques, maybe you can discuss in the C programming forum.Sorry, I can't help you
