### ISSUE TITLE
I have a problem with the synchronization of messages

### ISSUE THREAD

**Issue by JEFFERSON-HUERA** [Seeed-Studio/Seeed_Arduino_CAN#141]
Hello, I am developing a CAN-BUS network. I have a problem to set the nodes to send and receive the message according to the arbitration (priority).

**Comment by techie66** [comment]
I'm not sure I understand your issue. Can you give an example of desired behavior and what happens instead?

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
