### ISSUE TITLE
CAN extended (19 bit) frame cannot be detected by a receiver

### ISSUE THREAD

**Issue by markwkiehl** [Seeed-Studio/Seeed_Arduino_CAN#142]
The Seeed Arduino CAN library (mcp2515_can.h) can send an extended 19 bit CAN frame, but it cannot detect it as a receiver, 		nor can it decode the CAN ID correctly.  

Additionally, when sending an extended 29 bit frame, use the value of 0.01 for the frame type, not 0x02.  
CAN.MCP_CAN::sendMsgBuf(CANmsgId, 0x01, 8, canMsg);

**Comment by fastbike** [comment]
The CAN spec shows identifiers as 11 bit (standard) or 29 bit (extended).
AFAIK there is no 19 bit identifier.
The IDE control bit is 0x00 for standard CAN and 0x01 for extended CAN.
https://en.wikipedia.org/wiki/CAN_bus

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
