### ISSUE TITLE
Filters and masks do not seem to work properly

### ISSUE THREAD

**Issue by reldneb** [Seeed-Studio/Seeed_Arduino_CAN#147]
Example:
mask 0110 1000 1000 0x688
filter 0000 0000 0x000

ID1 0000 0001 0000
ID2 0000 0001 0001
ID3 0000 0001 0010
ID4 0000 0010 0100
ID5 0000 0001 0101
ID6 0001 0000 0000
ID7 0001 0000 0010
ID8 0001 0000 0011
ID9 0001 0000 0100
ID10 0000 0100 0111
ID11 0000 0100 0001

ID6 and ID7 are accepted once. Received only twice. After that nothing more is received. The other ID's are blocked. The script for the MCP2515 is the same in all Nano's, or Mega2560. I have also changed the MCP2515.
If I change the mask to 0x000 and the filter also to 0x000 nothing changes.
With the mask mask 0x7FC and the filter 0x010 I see some IDs more.
I use the rollover and the default frame with 11 bits for the ID.
Something is going wrong.

**Comment by DevZombi** [comment]
I am having this same exact issue. I can Mask and Filter extended IDs but can't filter standard IDs.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by reldneb** [comment]
Hello, I already finished my CAN project a few months ago and removed 12 Arduino boards from my motorhome.
The Can-Bus could not be filtered properly.
I have given up on this and have de-digitised the vehicle again. It took a lot of time and money but I still enjoyed it.

Thanks for the message

**Comment by Lesords** [comment]
OK, I understand.

Apologize again.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
