### ISSUE TITLE
Problem receiving high frequency can device

### ISSUE THREAD

**Issue by Zoylamb** [Seeed-Studio/Seeed_Arduino_CAN#152]
Using the shield on Arduino uno to receive datas from 2 CAN devices sending datas at 100Hz.
Using poll mode (not interruption) and reading at 500Hz on arduino (delay 2ms).

Sometime receiving datas (normal frame, 2 IDs, 8 bytes) is blocked due to error
Error given from checkerror function : return 5 and err value : 21

This behavior seems random and functions checkerrors, checkClearRxStatus and checkClearTxStatus didn't help.

What is this error?
How to correct it?

Thank you.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
