### ISSUE TITLE
Make lib compatible to 8 MHz MCP2515-boards

### ISSUE THREAD

**Issue by igittigitt** [Seeed-Studio/Seeed_Arduino_CAN#44]
Include changes made here https://github.com/peppeve/CAN_BUS_Shield to use boards with 8 instead of 16 MHz oscillator.

**Comment by ttlappalainen** [comment]
I just updated my changes to be based on latest Seeed and peppeve 8Mhz version + my own improvements. You can find it on https://github.com/ttlappalainen/CAN_BUS_Shield 
I'll also try to make pull to Seeed.

**Comment by loovee** [comment]
Look awesome, thanks for sharing.

**Comment by dzid26** [comment]
CAN.begin(CAN_500KBPS,MCP_8MHz)) 
I can confirm it works nowadays. You can probably close the issue.
