### ISSUE TITLE
Raspberry

### ISSUE THREAD

**Issue by djhoke88** [Seeed-Studio/Seeed_Arduino_CAN#47]
Hi, it can be connected to raspberry pi 3 ?

**Comment by loovee** [comment]
Hello, I am sorry that this's for Arduino.
If you want to feature your Pi with CAN Bus, you can try [Serial CAN Bus module](https://www.seeedstudio.com/Serial-CAN-BUS-Module-based-on-MCP2551-and-MCP2515-p-2924.html).
Thanks.
