### ISSUE TITLE
Interrupted handling with mcp_can

### ISSUE THREAD

**Issue by ttlappalainen** [Seeed-Studio/Seeed_Arduino_CAN#50]
Hi,

Thank you for merging my changes. 

Would you be interested of new class e.g. iMCP_CAN inherited from MCP_CAN, which would have full interrupt handling and buffers as I have on NMEA2000_mcp class? Now I have those handlers build in NMEA2000_mcp class, since MCP_CAN does not have interrupt handling. Other can libraries like due_can and FlexCan has interrupts build in, so I just use them. I thought to add interrupt handling for MCP_CAN, but there might be a problem with memory and code size on smaller boards like Arduino Uno. So making new iMCP_CAN class, it would not had any effect to old installations, but would give simple way to expand system to interrupts.

I could export rather easily my current code from NMEA2000_mcp to new class.

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.
