### ISSUE TITLE
Failed to enter configuration mode

### ISSUE THREAD

**Issue by chris-makaio** [Seeed-Studio/Seeed_Arduino_CAN#51]
This is strange...
`mcp2515_modifyRegister(MCP_CANCTRL, MODE_MASK, newmode);`
does not seem to change the mode, as the next `mcp2515_readRegister()` returns a different mode.

If I replace the modifyRegister by 
`mcp2515_setRegister(MCP_CANCTRL, newmode);`
it works..

**Comment by APokorny** [comment]
Or your MCP2515 needs some time to make the mode change. If you take the linux driver for reference, it does loop some time after a requested mode change.

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.
