### ISSUE TITLE
random fails, caused by unitialized filter registers RXF0..RXF5

### ISSUE THREAD

**Issue by CapitanoPedro** [Seeed-Studio/Seeed_Arduino_CAN#59]
Hi all,
i recently opened an issue  regarding problems with mcp_can in the NMEA2000 project (see below).

Altough at the first glimpse everything looked right, I ran into the problem, that all messages are rejected.
The library worked only well, if the filters are explicitely switched off (RXMn="11").
In the default mode nothing came in, all was rejected.
The filter masks after init are 0x00000000L and the 6 filters are uninitialized. 
I thought "this must be OK", because a nulled mask disables the filter.
But, this is not!
For whatever reason all this works only, if bit EXIDE is set in the filters.
With uninitialized filters the system randomly fails after system start.
Such problems (rejection, altough filters are zeroed) are described in various threads on the Internet.
Took a while for me to find out and also to find the real cause.

Please have a deeper look to the conversation I have had with Timo. There is more information
https://github.com/ttlappalainen/NMEA2000/issues/96

With the described fix my system eventually worked well.
The only question is, does it also run well with standard messages?
Maybe only one or two filters should get an EXIDE bit (????).
That should have to be discussed and tested.
But, definitely ... it no good idea to leave the six filters unitialized in mcp2515_init.

Regards and greetings

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.
