### ISSUE TITLE
Not compatible with CAN-Bus Shield 1.2

### ISSUE THREAD

**Issue by shinedown99** [Seeed-Studio/Seeed_Arduino_CAN#61]
Please support the "old" 1.2 version with this lib. It is in Europe still not availiable and Amazon does still ship the 1.2. So please don't stop supporting it.

**Comment by Jenkinlu001** [comment]
Thanks for your support, here is a detailed comparison of v1.2 and v2 :
http://wiki.seeedstudio.com/CAN-BUS_Shield_V2.0/

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.
