### ISSUE TITLE
Incorrect mask definition for RTR bit

### ISSUE THREAD

**Issue by sfyang** [Seeed-Studio/Seeed_Arduino_CAN#62]
In the header file "mcp_can_dfs.h", there is a bit mask for the RTR bit defined around line 69 as:
```C
#define MCP_RTR_MASK        0x40                                        // (1<<6) Bit 6
```
which indicates that the RTR bit is at the 6th bit (bit 5) of the 8bit register address.

However, according to the table "RIGESTER 4-5" on page 30 of the [datasheet of MCP2515](http://ww1.microchip.com/downloads/en/DeviceDoc/20001801H.pdf), the RTR bit is, in fact, at 5th bit (bit 4) of the RXBnIDL register, which means that the correct bit mask for RTR bit should be as following:
```C
#define MCP_RTR_MASK        0x10                                        // (1<<5) Bit 4
```
The incorrect bit mask could lead to misjudging of a data frame as remote frame if checking the bit with the incorrect mask.

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.
