### ISSUE TITLE
private variable MCP::ext_flg is not properly reset in the MCP_CAN::mcp2515_read_canMsg method`

### ISSUE THREAD

**Issue by sfyang** [Seeed-Studio/Seeed_Arduino_CAN#64]
When the `MCP_CAN::readMsgBufID()` method is called, the pointer of `MCP::ext_flg` is passed to `MCP_CAN::mcp2515_read_canMsg()` method to get the value of the IDE bit (Extended Identifier Flag bit) in the RXBnSIDL register. The [corresponding code segment](https://github.com/Seeed-Studio/CAN_BUS_Shield/blob/master/mcp_can.cpp#L783) is shown below:
```C++
  if ( (tbufdata[MCP_SIDL] & MCP_TXB_EXIDE_M) ==  MCP_TXB_EXIDE_M )
  { 
    /* extended id                  */
    *id = (*id << 2) + (tbufdata[MCP_SIDL] & 0x03);
    *id = (*id << 8) + tbufdata[MCP_EID8];
    *id = (*id << 8) + tbufdata[MCP_EID0];
    *ext = 1;
  }
```
In the segment, the `MCP::ext_flg` is set to 1 if the ID is an extended ID. However, the problem is, `MCP::ext_flg` will not be set to 0 if the ID read by the next call is a standard ID. This could lead to some strange result under the circumstance that, a call to the `MCP_CAN::isExtendedFrame()` method could return `true` for a standard frame if it was received right after a extended frame, since the `MCP::ext_flg` was set to `1` when the extended frame was read while not being reset to `0` for the following standard frame.

A possible and naive solution to this could be as following:
```C++
  if ( (tbufdata[MCP_SIDL] & MCP_TXB_EXIDE_M) ==  MCP_TXB_EXIDE_M )
  {
    /* extended id                  */
    *id = (*id << 2) + (tbufdata[MCP_SIDL] & 0x03);
    *id = (*id << 8) + tbufdata[MCP_EID8];
    *id = (*id << 8) + tbufdata[MCP_EID0];
    *ext = 1;
  } else {
    /* standard id */
    *ext = 0;
  }
```

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.
