### ISSUE TITLE
SPI 2nd Port

### ISSUE THREAD

**Issue by whcir911** [Seeed-Studio/Seeed_Arduino_CAN#66]
How do you use the 2nd SPI port with with this library?

**Comment by Jenkinlu001** [comment]
You can use ICSP pins or know MCP2515 stand-alone CAN controller with SPI interface :
https://raw.githubusercontent.com/SeeedDocument/CAN_BUS_Shield/master/resource/MCP2515.pdf

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.
