### ISSUE TITLE
Dual can bus

### ISSUE THREAD

**Issue by hugovw1976** [Seeed-Studio/Seeed_Arduino_CAN#70]
Can you modify this library to suport two Can bus shield's.
I want to have dual channel can bus like arduino due or teensy 3.6 but with the arduino uno.
Just modify this to have one board with CS on D10 and another on CS D9 
for send something like:
CAN1.sendMsgBuf(0x00, 0, 8, stmp1);
CAN2.sendMsgBuf(0x10, 0, 8, stmp2);

Thanks.

**Comment by coolping** [comment]
I feel the same way~~~ XD

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.
