### ISSUE TITLE
readMsgBuf doesn't reset interrupt flag after read buffer in mcp_can.cpp

### ISSUE THREAD

**Issue by davidcyr2000** [Seeed-Studio/Seeed_Arduino_CAN#71]
"MCP2515 RECEIVE FLAGS/INTERRUPTS: When a message is moved into either of the receive buffers, the appropriate RXnIF bit (CANINTF) is set.  This bit must be cleared by the MCU in order to allow a new message to be received into the buffer. This bit provides a positive lockout to ensure that the MCU has finished with the message before the MCP2515 attempts to load a new message into the receive buffer."

Code that fixes this problem is attached.  See the lines of code with "djc" in the comments.
[mcp_can.cpp.zip](https://github.com/Seeed-Studio/CAN_BUS_Shield/files/2391034/mcp_can.cpp.zip)

**Comment by dzid26** [comment]
Great! Now it works. I knew something along those lines was needed. It's strange it was missing.

**Comment by alexanderturner** [comment]
Why not submit a PR here?

**Comment by davidcyr2000** [comment]
What is a "PR"?    I had asked the module author to correct it, but got no response.

**Comment by alexanderturner** [comment]
Ah! If you create a new branch with your changes, you can then request it get merged in with the code in master. It’s easily googlable else I can do it for you.

**Comment by davidcyr2000** [comment]
Hi Alexander,
I spent a some time trying to figure out how to do this, but it isn't obvious!!!    I probably wouldn't get it right, so please feel free to do it.
The 8 lines of code added have "djc" in the comments.  Nothing else was changed.
Thanks!
David Cyr
________________________________

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.
