### ISSUE TITLE
Extended CAN Frames

### ISSUE THREAD

**Issue by davemoore1** [Seeed-Studio/Seeed_Arduino_CAN#72]
Connecting an Arduino+MCP to the OBDII port of a car which uses extended CAN frames has been a challenge. 

The bench test of connecting an Arduino+MCP to another Arduino+MCP works well (using Seeed libraries only for the standard CAN Frame. For extended CAN Frames I had to use Cory Fowler's instead https://github.com/coryjfowler/MCP_CAN_lib).

I have an Arduino+MCP acting as transmitter and another Arduino+MCP acting as a receiver. It works. Now, when I remove the wires that connect the 2 MCPs, the transmitter system is unable to send data, and gives an error message instead. Same happens when I connect the transmitter system to the OBDII port of a car (CAN H to pin 6. CAN L to pin 14). 

Is the transmitter waiting for some kind of ACK or what else do I need to consider? (I tried both removing and keeping the terminator resistor on the MCP. Still got the error).

Thanks

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.
