### ISSUE TITLE
The lesson explaining the bit length for smtp is 8 bytes, but when deciphered only generates 4 bytes when entered into calculator

### ISSUE THREAD

**Issue by roderek** [Seeed-Studio/Seeed_Arduino_CAN#73]

**Comment by Jenkinlu001** [comment]
unsigned char stmp[8] = {0, 1, 2, 3, 4, 5, 6, 7};
This is 8 bytes, so why is the calculation only 4 bytes?Can you give me some examples?
Thanks.

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.
