### ISSUE TITLE
standby mode

### ISSUE THREAD

**Issue by creativity3** [Seeed-Studio/Seeed_Arduino_CAN#75]
Hello
maybe somebody can put an example from this library using sleep/standby mode ?

**Comment by kaixxx** [comment]
Look at my pull request: https://github.com/Seeed-Studio/CAN_BUS_Shield/pull/77
Cheers!

**Comment by creativity3** [comment]
WOW!
thank you!
But it work with the library ?

**Comment by creativity3** [comment]
> Look at my pull request: #77
> Cheers!
WOW!
thank you!
But it work with the library ?

**Comment by kaixxx** [comment]
It will only work with the changes that I made in the library. I hope Seeedstudio will merge this soon. Since then, you can try out my fork here: https://github.com/kaixxx/CAN_BUS_Shield
Make sure to read the notes at the end of readme.md concerning sleep mode.

**Comment by creativity3** [comment]
thank you!

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.
