### ISSUE TITLE
Reading Messages Incorrectly

### ISSUE THREAD

**Issue by andrewaggie** [Seeed-Studio/Seeed_Arduino_CAN#76]
I have been using the mcp_can library with the example code to read CAN messages, but when my code reads messages, the ID's and data points are wrong. The code that I have been using is: https://github.com/andrewaggie/MCP_CAN/blob/master/CANTest.ino.

I am using the Diligent PmodCAN CAN-SPI shield, which is being read into a Particle Argon development board. I have verified that the connections between the Diligent shield and the Argon board are correct, but when I flash that code onto the board, the CAN messages read by the Argon board do not match the messages on the bus itself. When I put the board into Loopback mode, the messages come back correctly, but in the ListenOnly or Normal modes, the read messages are incorrect. The messages are being read, but the ID's, format, and data do not match what was received from the main Bus connections.

**Comment by connork216** [comment]
I am also having a very similar problem.

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.
