### ISSUE TITLE
CAN_83K3BPS vs CAN_83KBPS (keywords.txt)

### ISSUE THREAD

**Issue by dartrax** [Seeed-Studio/Seeed_Arduino_CAN#78]
Hi,
in keywords.txt there is the constant
`CAN_83KBPS`
defined and that's getting styled as a constant in Arduino IDE.
Shouldn't it be
`CAN_83K3BPS`
because that's compiling without errors?
The same may be the case for
`CAN_31K25BPS`

Probably forgotten at #49

**Comment by Jenkinlu001** [comment]
Thanks for your suggestion. There is an error that needs to be fixed.

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.
