### ISSUE TITLE
at command?

### ISSUE THREAD

**Issue by iuliancret** [Seeed-Studio/Seeed_Arduino_CAN#80]
hi
i am trying to change the baud rate up to 115200 but i have no succes in getting the shield to operate in config mode
First it was the issue of voltage, but i got it in the end
Can someone tell me how do you make the at commands work? 

Thanks

**Comment by Jenkinlu001** [comment]
Is Serial CAN-Bus used? You can see it :
https://docs.longan-labs.cc/1030001/
arduino example: https://github.com/Longan-Labs/Serial_CAN_Arduino

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.
