### ISSUE TITLE
Can BUS Shield init fail

### ISSUE THREAD

**Issue by mat-lol-mat** [Seeed-Studio/Seeed_Arduino_CAN#82]
I am stuck in a loop with the CAN Bus Init fail. I tried a few of the baud rate options (not all of them)
but I still seem to be stuck with this error
![Capture](https://user-images.githubusercontent.com/53049903/62337690-b3292d80-b4a3-11e9-8339-0dbf1362acdc.PNG)

**Comment by mat-lol-mat** [comment]
Currently I am trying to implement :
![image](https://user-images.githubusercontent.com/53049903/62338371-4ebb9d80-b4a6-11e9-9b63-9d94af44823d.png)

**Comment by mat-lol-mat** [comment]
Currently, I am trying to implement:
![image](https://user-images.githubusercontent.com/53049903/62338420-77dc2e00-b4a6-11e9-9afc-b359a66b6219.png)

**Comment by mat-lol-mat** [comment]
Figured out my initial issue, I had the wrong PIN. However, I am still stuck on not being able to read my vehicle information

**Comment by ICeZer0** [comment]
@markpwoodward I am getting the same issue running the HelloWorld CAN-BUS code. I have the shield and Arduino connected.  Is your baudrate set to 500k?

**Comment by ICeZer0** [comment]
Fixed. Simply set SPI_CS_PIN = 9 instead of 10 for the input param MCP_CAN CAN(SPI_CS_PIN);
​

**Comment by maqeelqureshi** [comment]
I am using SunFlower CAN Shield V3. https://www.aliexpress.com/item/32948283535.html
Setting CS to 10 resolves this error for me (default is 9 in example). 
But I don't receive any data.

**Comment by GunZi200** [comment]
Seems there is no issue here. Shouldn't this issue be closed?

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.

**Comment by Aniltudarmstadt** [comment]
Hey ,
im using the adruino board von Joy-it to calibrate the H2 sensor but it always shows "can init failed"

09:20:19.968 -> CAN init fail, retry...
09:20:20.262 -> CAN init fail, retry...
09:20:20.585 -> CAN init fail, retry...
09:20:20.909 -> CAN init fail, retry...
09:20:21.244 -> CAN init fail, retry...
09:20:21.568 -> CAN init fail, retry...
09:20:21.891 -> CAN init fail, retry...
09:20:22.214 -> CAN init fail, retry...
 how to solve this problem ?
can any one help me?

**Comment by Khalid-Hersafril-Flowcopter** [comment]
in my case, spi_cs_pin 10 works for me instead of 9
