### ISSUE TITLE
Clock parameter missing in CAN.begin() in all of the examples

### ISSUE THREAD

**Issue by greghol** [Seeed-Studio/Seeed_Arduino_CAN#93]
Clock parameter missing in CAN.begin() in all of the examples. i.e.

In receive_check.ino:

   25:  while (CAN_OK != CAN.begin(CAN_500KBPS, **clock** )) {            // init can bus : baudrate = 500k

clock param is missing from examples. This is important if the module is to interoperate with other devices not using the Seeed code. Crystal frequency need to go here depending on CAN module crystal frequency used. Most are 8MHz (MCP_8MHz) but code defaults to 16MHz (MCP_16MHz). Once I fixed this I could talk to my CAN analyzer since the speed then was actually 500kbps.

/*********************************************************************************************************
** Function name:           begin
** Descriptions:            init can and set speed
*********************************************************************************************************/
byte MCP_CAN::begin(byte speedset, **const byte clockset**) {
    pSPI->begin();
    byte res = mcp2515_init(speedset, **clockset**);

    return ((res == MCP2515_OK) ? CAN_OK : CAN_FAILINIT);
}

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.
