### ISSUE TITLE
Send Timeout in send function at low rates modes

### ISSUE THREAD

**Issue by jmoyola** [Seeed-Studio/Seeed_Arduino_CAN#95]
Low frames modes make timeout in send frames. P.E.: 10 or 20 KBPS in trame standard and 4 bytes of data return timeout (but the frame is send).

**Comment by jmoyola** [comment]
send timeout value 10 in declaration (mcp_can_dfs.h) is low value for low framerates
#define TIMEOUTVALUE    10

I haved test with 10KBPS and 250 and all its ok (for extended transmit frame)... i think must do:
  - increase to 500 (for 5KBPS).
or
  - convert this constant to variable and recalculate in function mcp2515_configRate:

mcp_can_dfs.h:
**//#define TIMEOUTVALUE  10**

mcp_can.h:
 private:
    **uint16_t TIMEOUTVALUE=10; // Default timeout**

mcp_can.cpp:
byte MCP_CAN::mcp2515_configRate(const byte canSpeed, const byte clock) {
...
case (MCP_16MHz) :
TIMEOUTVALUE=X
case (MCP_16MHz) :
TIMEOUTVALUE=X
....

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.
