### ISSUE TITLE
CanOpen

### ISSUE THREAD

**Issue by florentheman** [Seeed-Studio/Seeed_Arduino_CAN#96]
Is it possible to do canOpen with this shield? For example sending and recieving PDO and SDO messages? I cannot find anything about it in the documentation or sample projects.

**Comment by wdross** [comment]
Yes you can.
However, *you* need to create code that formats the PDO and SDO messages: this library is the underlying piece that transmits and receives the raw 8-byte messages with COBID.
I haven't found an Open Source CanOpen library myself; I've just made "enough" code to get a simple task accomplished with this hardware.


    On Tuesday, June 16, 2020, 3:30:33 PM EDT, Floren <notifications@github.com> wrote:  
 
 


Is it possible to do canOpen with this shield? For example sending and recieving PDO and SDO messages? I cannot find anything about it in the documentation or sample projects.

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.
