### ISSUE TITLE
Filtering working only when Arduino nano is supplied with USB

### ISSUE THREAD

**Issue by zentT** [Seeed-Studio/Seeed_Arduino_CAN#99]
Can someone explains me why the filtering mode is only working when the nano is plugged with USB ?
Is anything is this library relying on the USB to make the filtering work ? Thanks

**Comment by Pillar1989** [comment]
remove this codo ? 
```C++
 while(!Serial){};
```

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.
